# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
    ]

    operations = [
    ]
