# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u540d\u5b57')),
                ('img1', models.CharField(max_length=256, verbose_name='\u56fe\u7247')),
                ('detail1', models.TextField(verbose_name='\u4ea7\u54c1\u6982\u89c8')),
                ('detail2', models.TextField(verbose_name='\u8be6\u7ec6\u53c2\u6570')),
                ('detail3', models.TextField(verbose_name='\u8d44\u6599\u4e0b\u8f7d')),
                ('detail4', models.TextField(verbose_name='\u4ea7\u54c1\u6f14\u793a')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1',
                'verbose_name_plural': '\u4ea7\u54c1',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u5206\u7c7b',
                'verbose_name_plural': '\u4ea7\u54c1\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ProductType'),
        ),
    ]
