# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36, verbose_name='\u5c5e\u6027')),
                ('detail1', models.TextField(verbose_name='\u5185\u5bb9')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u8be6\u7ec6',
                'verbose_name_plural': '\u4ea7\u54c1\u8be6\u7ec6',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail4',
        ),
        migrations.AddField(
            model_name='product',
            name='home_recommend',
            field=models.BooleanField(default=False, verbose_name='\u9996\u9875\u63a8\u8350'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='\u5bfc\u822a\u63a8\u8350'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(upload_to=b'', verbose_name='\u4ea7\u54c1\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ProductType', verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Product', verbose_name='\u5546\u54c1'),
        ),
    ]
