# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160423_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='detail1',
            field=models.TextField(default='', verbose_name='\u4ea7\u54c1\u7279\u70b9'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail2',
            field=models.TextField(default='', verbose_name='\u4ea7\u54c1\u89c4\u683c'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail3',
            field=models.TextField(default='', verbose_name='\u8f6f\u4ef6\u529f\u80fd'),
        ),
        migrations.AddField(
            model_name='product',
            name='detail4',
            field=models.TextField(default='', verbose_name='\u5178\u578b\u5e94\u7528'),
        ),
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
