# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160423_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail5',
            field=models.TextField(default='', verbose_name='\u8ba2\u8d2d\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='uid',
            field=models.IntegerField(null=True, unique=True, verbose_name='uid'),
        ),
    ]
