# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160423_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['id'], 'verbose_name': '\u4ea7\u54c1\u5206\u7c7b', 'verbose_name_plural': '\u4ea7\u54c1\u5206\u7c7b'},
        ),
        migrations.AddField(
            model_name='producttype',
            name='img1',
            field=models.ImageField(null=True, upload_to=b'', verbose_name='\u7c7b\u578b\u56fe\u7247'),
        ),
    ]
