# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20160423_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='', upload_to=b'', verbose_name='\u7c7b\u578b\u56fe\u7247')),
                ('href', models.URLField(null=True, verbose_name='\u8df3\u8f6c\u5730\u5740')),
                ('sort_num', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id', '-sort_num'],
                'verbose_name': '\u4e3b\u9875\u8f6e\u64ad\u56fe',
                'verbose_name_plural': '\u4e3b\u9875\u8f6e\u64ad\u56fe',
            },
        ),
    ]
