# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_homebaner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('ptype', models.IntegerField(choices=[(0, '\u6700\u65b0\u8d44\u8baf'), (1, '\u516c\u53f8\u4ecb\u7ecd')], verbose_name='\u7c7b\u578b')),
                ('detail', models.TextField(default='', verbose_name='\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5173\u4e8e\u7f51\u7855',
                'verbose_name_plural': '\u5173\u4e8e\u7f51\u7855',
            },
        ),
        migrations.AlterField(
            model_name='homebaner',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='homebaner',
            name='href',
            field=models.URLField(blank=True, null=True, verbose_name='\u8df3\u8f6c\u5730\u5740'),
        ),
    ]
