# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160424_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='home_recommend',
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='\u7b80\u5355\u4ecb\u7ecd'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail1',
            field=models.TextField(blank=True, default='', verbose_name='\u4ea7\u54c1\u7279\u70b9'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail2',
            field=models.TextField(blank=True, default='', verbose_name='\u4ea7\u54c1\u89c4\u683c'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail3',
            field=models.TextField(blank=True, default='', verbose_name='\u8f6f\u4ef6\u529f\u80fd'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail4',
            field=models.TextField(blank=True, default='', verbose_name='\u5178\u578b\u5e94\u7528'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail5',
            field=models.TextField(blank=True, default='', verbose_name='\u8ba2\u8d2d\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='\u9996\u9875\u63a8\u8350'),
        ),
    ]
