# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160424_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img1',
            new_name='img',
        ),
    ]
