# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160424_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('ptype', models.IntegerField(choices=[(0, '\u4e0b\u8f7d\u4e2d\u5fc3'), (1, '\u552e\u540e\u670d\u52a1')], default=0, verbose_name='\u7c7b\u578b')),
                ('detail', models.TextField(default='', verbose_name='\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u670d\u52a1\u652f\u6301',
                'verbose_name_plural': '\u670d\u52a1\u652f\u6301',
            },
        ),
    ]
