# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_supports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='\u65b9\u6848\u6807\u9898')),
                ('detail', models.TextField(default='', verbose_name='\u5185\u5bb9')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('ptype', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.ProductType', verbose_name='\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u65b9\u6848',
                'verbose_name_plural': '\u65b9\u6848',
            },
        ),
        migrations.CreateModel(
            name='SolutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(null=True, unique=True, verbose_name='uid')),
                ('name', models.CharField(max_length=30, verbose_name='\u7c7b\u578b')),
                ('img', models.ImageField(null=True, upload_to=b'', verbose_name='\u7c7b\u578b\u56fe\u7247')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u65b9\u6848\u5206\u7c7b',
                'verbose_name_plural': '\u65b9\u6848\u5206\u7c7b',
            },
        ),
    ]
